### ISSUE TITLE
Messages not being recieved by useMsg()

### ISSUE THREAD

**Issue by inabreslin** [ltiseni94/roslib-reactjs#1]
When I use the useMsg() hook within a child component within Subscriber, the object const message = useMsg(); appears to be empty even when there are items being streamed to the topic.

**Comment by ltiseni94** [comment]
Could you please paste the code here? Could you verify that websocket is working?

**Comment by inabreslin** [comment]
From the ros websocket, it says the client is connected and I am able to publish and it also says the client is subscribed to the right topic but I cannot view any messages sent to that topic.

`import React, { useState, useRef, useEffect} from "react";
import {RosConnect, Publisher, Subscriber, useMsg} from "roslib-reactjs";


function Play() {
  function Score (){
    const message = useMsg();
    console.log(Object.keys(message));
    // console.log(message.score);
    return (
      <div className="score">
        <h2>
          {message.data}
        </h2>
      </div>
    )
  }

  return (
    <div className="play">
      <div className="container">
        <div className="row align-items-center my-3 justify-content-center">
          <div className="col-lg-5">
          <div className="text-center mt-5">
            <h2 className="font-weight-light"> {title} </h2>
          </div>
          </div>
        </div>
        <div className="row align-items-center my-3 justify-content-center">
          <RosConnect
                url="ws://192.xxx.x.xxx:9090"
                autoconnect
                timeout={1000}
          >
              <Publisher
                  name="/danceControl"
                  type="std_msgs/String"
                  autoRepeat
                  rate={10.0}
                  queue_size={1}
                  message={{data: controlString()}}
              />
              <Subscriber
                  name="/score"
                  type="std_msgs/Int32"
                  rate={10.0}
                  queue_size={1}
              />
                <Score />
          </RosConnect>
        </div>
      </div>
    </div>
  );
}

export default Play;`

**Comment by ltiseni94** [comment]
Please, try again with the Score wrapped into the Subscriber like this:

<Subscriber
       name="/score"
       type="std_msgs/Int32"
       rate={10.0}
       queue_size={1}
>
    <Score/>
</Subscriber>

**Comment by inabreslin** [comment]
When I add the closing tag I get the error of: Expected corresponding JSX closing tag for 'RosConnect'

**Comment by ltiseni94** [comment]
Is your code exactly like this one?

import React, { useState, useRef, useEffect} from "react";
import {RosConnect, Publisher, Subscriber, useMsg} from "roslib-reactjs";


function Play() {
  function Score (){
    const message = useMsg();
    console.log(Object.keys(message));
    // console.log(message.score);
    return (
      <div className="score">
        <h2>
          {message.data}
        </h2>
      </div>
    )
  }

  return (
    <div className="play">
      <div className="container">
        <div className="row align-items-center my-3 justify-content-center">
          <div className="col-lg-5">
          <div className="text-center mt-5">
            <h2 className="font-weight-light"> Title</h2>
          </div>
          </div>
        </div>
        <div className="row align-items-center my-3 justify-content-center">
          <RosConnect
                url="ws://192.xxx.x.xxx:9090"
                autoconnect
                timeout={1000}
          >
              <Publisher
                  name="/danceControl"
                  type="std_msgs/String"
                  autoRepeat
                  rate={10.0}
                  queue_size={1}
                  message={{data: "hi"}}
              />
              <Subscriber
                  name="/score"
                  type="std_msgs/Int32"
                  rate={10.0}
                  queue_size={1}
              >
                <Score />
              </Subscriber>
          </RosConnect>
        </div>
      </div>
    </div>
  );
}

export default Play;

**Comment by ltiseni94** [comment]
Another thing I would suggest it's to put the Score definition out of the Play function component. I don't know if React recognize Score as a component in this way, maybe there are problem with the useMsg hook for that.

**Comment by inabreslin** [comment]
I believe it is working now, thank you. It must have been a typo of some sort.
